#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Firebase project setup for Bookmarked"

# ── Stage 1: create the project ────────────────────────────────────────────
stage "Create the Firebase project"
say "This creates the project everything else in this wizard attaches to."
open_url "https://console.firebase.google.com/"
step "Click 'Add project', name it e.g. 'bookmarked' (or 'bookmarked-dev' if you want separate dev/prod projects later)."
step "You can decline Google Analytics for this project — it's not part of the migration plan."
step "Once created, open Project settings (gear icon, top left) → General tab."
ask FIREBASE_PROJECT_ID "Paste the 'Project ID' shown there (not the display name):"
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
note "This ID goes into app/lib/firebase_options.dart once Claude scaffolds FlutterFire."

# ── Stage 2: upgrade to Blaze ───────────────────────────────────────────────
stage "Upgrade to the Blaze (pay-as-you-go) plan"
warn "This attaches real billing to the project. Cloud Storage and Cloud Functions require it, but Blaze keeps the same free daily quotas as the free Spark plan — see docs/adr/0001-migrate-postgres-fastapi-to-firebase.md for why we're accepting this instead of a hard cap (Firebase has no true hard spend cap)."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/usage/details"
step "Click 'Modify plan' (or the Spark/Blaze badge), choose Blaze, and link or create a Cloud Billing account with a payment method."
if confirm "Confirm: the project is now on the Blaze plan with billing linked?"; then
  note "Blaze confirmed."
else
  warn "Stopping here — nothing after this point works without Blaze (Storage/Functions need it). Re-run this wizard once it's done."
  exit 1
fi

# ── Stage 3: budget alert ───────────────────────────────────────────────────
stage "Set a low-threshold budget alert"
say "Budget alerts only notify — they don't stop spending (see the ADR) — but they're the agreed cost backstop for this project."
open_url "https://console.cloud.google.com/billing/budgets?project=$FIREBASE_PROJECT_ID"
step "Click 'Create budget'. Scope it to this project."
step "Set the budget amount to something tiny, e.g. \$1, and keep the default alert thresholds (50%/90%/100%) — or add a 1% threshold for the earliest possible warning."
step "Make sure your own email is a recipient (it is by default for project billing admins)."
pause "Press Enter once the budget is saved."

# ── Stage 4: register the Android app ───────────────────────────────────────
stage "Register the Android app"
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/settings/general"
step "Under 'Your apps', click the Android icon to add an app."
step "Android package name: com.bookmarked.bookmarked (must match exactly — it's read from app/android/app/build.gradle.kts)."
step "Nickname: anything, e.g. 'Bookmarked Android'. SHA-1 can be skipped now, but Google Sign-In fails on Android (even debug builds) until the SHA-1 and SHA-256 of keystore/debug.keystore are added under Project settings > Your apps > Add fingerprint — see AGENTS.md."
step "Click through 'Register app', then 'Download google-services.json'."
say "Save the downloaded file — you'll place it at app/android/app/google-services.json in the last stage."
pause "Press Enter once google-services.json is downloaded."

# ── Stage 5: register the iOS app ───────────────────────────────────────────
stage "Register the iOS app"
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/settings/general"
step "Under 'Your apps', click the iOS icon (Apple) to add an app."
step "iOS bundle ID: com.bookmarked.bookmarked (must match exactly — it's read from app/ios/Runner.xcodeproj/project.pbxproj)."
step "Nickname: anything, e.g. 'Bookmarked iOS'. App Store ID can be left blank."
step "Click through 'Register app', then 'Download GoogleService-Info.plist'."
say "Save the downloaded file — you'll place it at app/ios/Runner/GoogleService-Info.plist in the last stage."
pause "Press Enter once GoogleService-Info.plist is downloaded."

# ── Stage 6: App Check ───────────────────────────────────────────────────────
stage "Enable App Check"
say "App Check cuts down on abuse from clients that aren't your real app — cheap insurance given there's no hard spend cap."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/appcheck"
step "Register the Android app with the 'Play Integrity' provider."
step "Register the iOS app with the 'App Attest' provider (falls back to DeviceCheck on older devices/simulators automatically)."
step "Leave enforcement in 'Monitor' mode for now — switch to 'Enforce' once the app is actually making Firestore/Storage/Auth calls successfully, otherwise you'll lock yourself out during development."
pause "Press Enter once both apps show up under App Check."

finish

printf '\n%s%sPlace the two downloaded files here in the repo:%s\n' "$BOLD" "$BLUE" "$RESET"
printf '  %s app/android/app/google-services.json\n' "$GREEN"
printf '  %s app/ios/Runner/GoogleService-Info.plist%s\n\n' "$GREEN" "$RESET"
note "Both are gitignored by default in Flutter/Firebase projects — verify with 'git status' that they don't show up as untracked before committing anything else."
note "Once they're in place, tell Claude — it'll wire up firebase_options.dart and the rest of the FlutterFire scaffolding around them."
